module.exports = [
    {
        name:'삼성전자',
        price:"70,100",
    },
    {
        name:'카카오',
        price:"91,600",
    },
    {
        name:'NAVER',
        price:"307,000",
    },
    {
        name:'셀트리온',
        price:"165,000",
    },
    {
        name:'SK하이닉스',
        price:"119,500",
    },
    {
        name:'삼성바이오로직스',
        price:"764,000",
    },
    {
        name:'삼성SDI',
        price:"511,000",
    },
    {
        name:'DL이앤씨우',
        price:"68,600",
    },
    {
        name:'비에이치',
        price:"19,300",
    },
    {
        name:'현대차',
        price:"168,000",
    },
]

